name: security
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dash_shield:
    git:
      url: https://github.com/Ahmad-Ayman/flutter_dash_shield_plugin.git
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0


dev_dependencies:
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  lints: ^6.0.0
  test: ^1.26.3


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)


  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true