name: core
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  logger:
  flutter_screenutil: ^5.9.3
  data:
    path: ../data
  dio:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  lints: ^6.0.0
  test: ^1.26.3

